version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: America/Bogota
    labels:
      - dependencies
    commit-message:
      prefix: "chore"
