import { NavItem } from './shared/models/nav.types';

export const NAV_ITEMS: NavItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: 'home',
    route: '/dashboard',
    roles: ['admin', 'lider_compras', 'lider_tienda', 'barista'],
    orden: 1,
  },
  {
    id: 'tiendas',
    label: 'Tiendas',
    icon: 'building-storefront',
    route: '/tiendas',
    roles: ['admin'],
    orden: 2,
  },
  {
    id: 'empleados',
    label: 'Empleados',
    icon: 'users',
    route: '/empleados',
    roles: ['admin'],
    orden: 3,
  },
  {
    id: 'catalogo',
    label: 'Catálogo',
    icon: 'squares-2x2',
    route: '/catalogo',
    roles: ['admin', 'lider_compras', 'lider_tienda', 'barista'],
    orden: 4,
    children: [
      {
        id: 'categorias',
        label: 'Categorías',
        icon: 'tag',
        route: '/categorias',
        roles: ['admin'],
        orden: 1,
      },
      {
        id: 'unidades-medida',
        label: 'Unidades de medida',
        icon: 'scale',
        route: '/unidades-medida',
        roles: ['admin'],
        orden: 2,
      },
      {
        id: 'proveedores',
        label: 'Proveedores',
        icon: 'truck',
        route: '/proveedores',
        roles: ['admin'],
        orden: 3,
      },
      {
        id: 'items',
        label: 'Items',
        icon: 'cube',
        route: '/items',
        roles: ['admin', 'lider_compras', 'lider_tienda', 'barista'],
        orden: 4,
      },
    ],
  },
  {
    id: 'menu',
    label: 'Menú y Recetas',
    icon: 'book-open',
    route: '/menu',
    roles: ['admin'],
    orden: 5,
  },
  {
    id: 'inventario',
    label: 'Inventario',
    icon: 'clipboard-document-list',
    route: '/inventario',
    roles: ['admin', 'lider_tienda', 'barista'],
    orden: 6,
    children: [
      {
        id: 'iniciar-conteo',
        label: 'Iniciar Conteo',
        icon: 'document-plus',
        route: '/inventario/iniciar',
        roles: ['admin', 'lider_tienda', 'barista'],
        orden: 1,
      },
      {
        id: 'historial',
        label: 'Historial',
        icon: 'clock',
        route: '/inventario/historial',
        roles: ['admin', 'lider_tienda', 'barista'],
        orden: 2,
      },
    ],
  },
  {
    id: 'mermas',
    label: 'Mermas',
    icon: 'trash',
    route: '/mermas',
    roles: ['admin', 'lider_tienda'],
    orden: 7,
  },
  {
    id: 'pedidos',
    label: 'Pedidos',
    icon: 'shopping-cart',
    route: '/pedidos',
    roles: ['admin', 'lider_compras', 'lider_tienda', 'barista'],
    orden: 8,
  },
  {
    id: 'caja-menor',
    label: 'Caja Menor',
    icon: 'banknotes',
    route: '/caja-menor',
    roles: ['admin', 'lider_tienda'],
    orden: 9,
  },
  {
    id: 'ventas',
    label: 'Ventas / POS',
    icon: 'chart-bar',
    route: '/ventas',
    roles: ['admin', 'lider_tienda'],
    orden: 10,
  },
  {
    id: 'demanda',
    label: 'Demanda',
    icon: 'presentation-chart-line',
    route: '/demanda',
    roles: ['admin', 'lider_compras'],
    orden: 11,
  },
];
